### ISSUE TITLE
Add IGCSDOF support

### ISSUE THREAD

**Issue by originalnicodr** [originalnicodr/CinematicUnityExplorer#66]
### Describe the issue

It would be very interesting to add [IGCSDOF](https://opm.fransbouma.com/igcsdof.htm) support to the project. Unfortunately, it might require some serious work to be done (particularly with hooking up the mod with reshade).

We could use @ghostinthecamera implementation of the system as a reference:
- [System.cpp](https://github.com/ghostinthecamera/IGCS-GITC/blob/6a0335f76130a879d37c785aad64a2a97290d564/Cameras/Armored%20Core%206/InjectableGenericCameraSystem/System.cpp#L535)
- [GameCameraData.h](https://github.com/ghostinthecamera/IGCS-GITC/blob/6a0335f76130a879d37c785aad64a2a97290d564/Cameras/Armored%20Core%206/InjectableGenericCameraSystem/GameCameraData.h#L84)
- [Globals.h](https://github.com/ghostinthecamera/IGCS-GITC/blob/6a0335f76130a879d37c785aad64a2a97290d564/Cameras/Armored%20Core%206/InjectableGenericCameraSystem/Globals.h#L97)
- [Camera.h](https://github.com/ghostinthecamera/IGCS-GITC/blob/6a0335f76130a879d37c785aad64a2a97290d564/Cameras/Armored%20Core%206/InjectableGenericCameraSystem/Camera.h#L65)

**Comment by ghostinthecamera** [comment]
You will also need to look at:

- [CameraToolsData.h](https://github.com/ghostinthecamera/IGCS-GITC/blob/6a0335f76130a879d37c785aad64a2a97290d564/Cameras/Armored%20Core%206/InjectableGenericCameraSystem/CameraToolsData.h)
- [CameraManipulator.cpp](https://github.com/ghostinthecamera/IGCS-GITC/blob/6a0335f76130a879d37c785aad64a2a97290d564/Cameras/Armored%20Core%206/InjectableGenericCameraSystem/CameraManipulator.cpp)

and a few others

**Comment by originalnicodr** [comment]
Done by @etra0 the :goat: on f557d3d
