### ISSUE TITLE
[Bug]: Input does not work

### ISSUE THREAD

**Issue by alan42521** [originalnicodr/CinematicUnityExplorer#75]
### Are you on the latest version of CinematicUnityExplorer?

- [X] Yes, I'm on the latest version of CinematicUnityExplorer.

### Which release are you using?

BepInEx Unity IL2CPP CoreCLR

### Which game did this occur on?

![捕获](https://github.com/originalnicodr/CinematicUnityExplorer/assets/108172351/6b522c55-9f61-4abb-a355-07d3be7a3d45)

### Describe the issue.

There is not response with key input

**Comment by originalnicodr** [comment]
Could you specify what game is this happening on, please?

**Comment by alan42521** [comment]
Syahata's bad day

**Comment by alan42521** [comment]
I could not open and close the panel by pressing F7
