### ISSUE TITLE
[Enhancement] Add an object inspector button to teleport it to Freecam coordinates

### ISSUE THREAD

**Issue by ertup0** [originalnicodr/CinematicUnityExplorer#80]
### Describe the new feature or enhancement

some games disable geometry/lights when the player is in a different part of the scene. You can manually teleport player around the scene by just finding the player object coordinates and copying freecam coordinates, but it would be nice to have a hotkey for teleporting.
I know that automatically finding player object is not easy so an ability to select player object from scene manually would be good

**Comment by originalnicodr** [comment]
Finding the player object might be easier with the Animator panel. Normally the player has an animator component so it can be found on that panel.

I do agree that manually copying coordinates can often be annoying (hitting control to do ctrl + v will move the camera down with the default hotkeys). A button that instantly copies camera coordinates over could be useful indeed.

Will rename the ticket to instead represent that 😃

**Comment by originalnicodr** [comment]
Sorry for the delay here, done on f3b1546. Feel free to test the nightly build! 😄
