### ISSUE TITLE
[Other]: add chinese support

### ISSUE THREAD

**Issue by dfdfsdf-hub** [originalnicodr/CinematicUnityExplorer#85]
### Describe the issue

add chinese support

**Comment by originalnicodr** [comment]
Hey there! Unfortunately, my time and resources are limited, and the project itself isn't in a robust enough position for multi-language support to make sense. So I will have to close this as not planned for now, sorry.

On the other hand, if what you need is not specifically features from this fork (camera paths, bone control, etc) and only native UnityExplorer features (explore objects and modify their properties) then you can check out this fork that seems to be a Chinese translation:

https://github.com/Gktwo/UnityExplorerchinese
