### ISSUE TITLE
[Enhancement]: Block free camera input when CUE displayed or in search

### ISSUE THREAD

**Issue by AnticOwl** [originalnicodr/CinematicUnityExplorer#97]
### Describe the new feature or enhancement

Noticed that when in Freecam, typing something in a search box in CUE (bones by example) would also interact with the camera input and move it. 
Would it be possible to implement something that when in CUE all camera input are blocked?

**Comment by originalnicodr** [comment]
Fixed on 6111c17. Hopefully, it doesn't affect performance too much.
